# Redis数据库索引（默认为0）
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait:
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
    timeout: 1000
  application:
    name: redis
  profiles:
    active: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
server:
  port: 0
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    # 下划线自动转驼峰命名法
    map-underscore-to-camel-case: true
security:
  user:
    name: user
    password: 123456
  basic:
    enabled: false